# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zvUA1ZLkG6O_iqcxhyRsfkr4wltq0u_E
"""

pip install requests beautifulsoup4 sqlalchemy

import requests
from bs4 import BeautifulSoup
from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime

DATABASE_URL = "sqlite:///congestion_data.db"
engine = create_engine(DATABASE_URL)
Base = declarative_base()

class CongestionData(Base):
    __tablename__ = 'congestion_data'

    id = Column(Integer, primary_key=True, index=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    congestion_info = Column(Text)

Base.metadata.create_all(bind=engine)

url = "https://www.jreast.co.jp/train-konzatsu/chuo_local.pdf"

response = requests.get(url)

soup = BeautifulSoup(response.text, 'html.parser')

if soup.find('dd',class_='trouble'):
    message = '東西線は遅延しています'
else:
    message = '東西線は通常運転です'

print(message)

Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)
db = Session()

url = "https://www.jreast.co.jp/train-konzatsu/chuo_local.pdf"
response = requests.get(url)
congestion_info = response.text

new_congestion_data = CongestionData(congestion_info=congestion_info)
db.add(new_congestion_data)
db.commit()
db.close()

